### ISSUE TITLE
Threadsafe code 

### ISSUE THREAD

**Issue by SaddamBInSyed** [grebtsew/Object-and-facial-detection-in-python#3]
Hi .

Thanks for your work.

since shared Variables are being used by multiple threads, how we handled read and write operation on the same variable.?

I could not see any thread lock method or .copy() method inside the code.

Please advise.

**Comment by grebtsew** [comment]
Hi @SaddamBInSyed !

To be fair thread-safety with locks/semaphores and such should be used in all multithreaded implementations and could be added to this implementation. But due to the Global Interprenter Lock used by the python programming language, locks won't be needed unless you work with Python-bytecode. You can read more about that here:

https://wiki.python.org/moin/GlobalInterpreterLock

I'd say it's one of many perks with Python. However it is not entirely failsafe. We would lose shared data if the amounts were increased too much.

Hope that answers your question.

Cheers,
@grebtsew

**Comment by grebtsew** [comment]
To clarify further, what is happening when two threads write to the same variable is that the threads overwrite the variable in a first in first out (FIFO) way. 

And several threads can read the variable at the same time. 

One disadvantage of these protected objects that python creates is that it is slower than alternative languages.

Cheers,
@grebtsew

**Comment by SaddamBInSyed** [comment]
understood. 

thanks for the detail.
